version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: pasific-capital-db
    restart: always
    environment:
      POSTGRES_USER: pasific
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pasific_capital
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: pasific-capital-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
